### ISSUE TITLE
Copy XMP data from file to file corrupts exif data

### ISSUE THREAD

**Issue by LidiaMirkin** [adobe/XMP-Toolkit-SDK#30] opened 2021-03-25 13:45 UTC
Hello

The following code corrupts exif meta data for some files.

XMP_OptionBits options = 0;
SXMPFiles::Initialize(options);
SXMPMeta meta;
{
    SXMPFiles myFile;
    XMP_OptionBits opts = kXMPFiles_OpenForUpdate | kXMPFiles_OpenUseSmartHandler;
    
    ok = myFile.OpenFile("from.jpg", kXMP_UnknownFile, opts);
    if (ok)
    {
	    ok = myFile.GetXMP(&meta);
    }
}

SXMPFiles myFile;
XMP_OptionBits opts = kXMPFiles_OpenForUpdate | kXMPFiles_OpenUseSmartHandler;
bool ok = myFile.OpenFile("to.jpg", kXMP_UnknownFile, opts);
myFile.PutXMP(meta);
myFile.CloseFile();

The final.jpg contains wrong DateTimeOriginal field. ( time is truncated - please see attached error.jpg screenshot
![error](https://user-images.githubusercontent.com/45731239/112482676-fd4dd980-8d80-11eb-8e56-0e82834e0aed.jpg)
)

Attached are 3 files illustrating the problem
![to](https://user-images.githubusercontent.com/45731239/112481767-05f1e000-8d80-11eb-9930-3e7f736b8883.jpg)
![final](https://user-images.githubusercontent.com/45731239/112481770-07230d00-8d80-11eb-95a9-dd983f6dc032.jpg)
![from](https://user-images.githubusercontent.com/45731239/112481773-07230d00-8d80-11eb-8a7f-09e82b060937.jpg)

Could you advice if it is bug in SDK or something wrong with my code ?

Thank you,
Lidia.

**Comment by arpitapanda05** [comment] 2021-05-05 07:07
Hi Lidia,
could you please attach the original file which has the correct dateTimeOrigial field?

**Comment by maupadhyay** [comment] 2023-12-19 06:25
This issue seems to be duplicate of https://github.com/adobe/XMP-Toolkit-SDK/issues/50, Which has been fixed and released with [July 2023 Release](https://github.com/adobe/XMP-Toolkit-SDK/releases/tag/v2023.07).
Can you please try with above version and let us know in case if you still face the issue. Closing this issue.

**Closed by maupadhyay** 2023-12-19 06:25 UTC
